version: '3'
services:
  db:
  # データベースmysqlを指定
    image: mysql:8.0
    command:
    --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
      # ローカル側(./src/db/mysql_data)をdocker側(/var/lib/mysql)に同期する
    enviroment:
      MYSQL_ROOT_PASSWORD: password
  web:
  # railsを指定
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    # railsサーバーを起動してポートを3000番を指定、IPアドレスのbindを0.0.0.0でどこでもOKにしている
    volumes:
      - ./src:/app
      # srcディレクトリ内をdocker内のappディレクトリに同期する
    ports:
      - "3000:3000"
    depends_on:
      - db
      # webサービスはdbサービスに依存している